@startuml superclase 

interface Collection implements Iterable {}

interface List implements Collection {}
interface Set implements Collection {}
interface Map implements Collection {}
interface Queue implements Collection {}

@enduml 