@startuml superclase 
abstract class Figura {
    +calcularArea():double 
    +calcularPerimetro():double
}

class Rectangulo extends Figura {}
class Triangulo extends Figura {}
class Circulo extends Figura {}
@enduml 